name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
      env:
        CI: true  
    - name: upload to cos
      if: success()
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shanghai.aliyuncs.com"
        access-key-id: "${{ secrets.ALI_CLOUD_SECRET_ID }}"
        access-key-secret: "${{ secrets.ALI_CLOUD_SECRET_KEY }}"
        sts-token: ""
    - run: ossutil cp -rf dist oss://emilystories/
